### ISSUE TITLE
Unhandled puppet type with awesome_print

### ISSUE THREAD

**Issue by logicminds** [nwops/puppet-debugger#59]
/Users/cosman/nwops/example42/puppet-tp/.bundle/gems/puppet-debugger-0.8.1/lib/awesome_print/ext/awesome_puppet.rb:35:in `awesome_puppet_type': undefined method `to_hash' for #<Puppet::Pops::Types::PResourceType:0x007fe2e42fbec0> (NoMethodError)
Did you mean?  to_s
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:26:in `format'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:115:in `unnested'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:74:in `awesome'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:91:in `pre_ruby19_syntax'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:51:in `block (2 levels) in printable_hash'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/indentator.rb:13:in `indent'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:63:in `increase_indentation'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/base_formatter.rb:113:in `indented'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:47:in `block in printable_hash'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:46:in `map!'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:46:in `printable_hash'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:35:in `multiline_hash'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatters/hash_formatter.rb:18:in `format'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:79:in `awesome_hash'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:26:in `format'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:115:in `unnested'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:74:in `awesome'
	from /Users/cosman/nwops/example42/puppet-tp/.bundle/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'

**Comment by logicminds** [comment]
It appears the to_hash method on puppet types was removed in puppet
